name: npm publish on tag

on:
  push:
    tags:
      - "*"
jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.10.0"
          registry-url: "https://registry.npmjs.org/"
      - name: Get version from tag
        id: tag-name
        run: echo "TAGNAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Clean version tag
        id: tag-version
        run: |
          TAGNAME=${{steps.tag-name.outputs.TAGNAME}}
          echo "VERSION=${TAGNAME//eco-}" >> $GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@v3
      - name: NodeJs version
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"
      - name: npm version
        run: npm i -g npm@8.1        
      - name: npm install
        run: |
          echo "Changing Directory to ngrx-http-tracking"
          cd ngrx-http-tracking
          ls
          sed -i "s/#{GITHUB_TAG_VERSION}#/${{ steps.tag-version.outputs.VERSION }}/g" projects/ngrx-http-tracking/package.json
          sed -i "s/#{GITHUB_TAG_VERSION}#/${{ steps.tag-version.outputs.VERSION }}/g" package.json
          npm install
      - name: npm build & publish
        run: |        
          echo "Changing Directory to ngrx-http-tracking"
          cd ngrx-http-tracking
          npm run publish:ngrx-http-tracking
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
